export const GETGOODSLIST = 'GETGOODSLIST' // 获取商品列表

export const ADDGOODS = 'ADDGOODS' //  添加商品

export const GETGOODSDETAIL = 'GETGOODSDETAIL' // 获取商品详情

export const GETBUTTONSTATUS = 'GETBUTTONSTATUS' // 商品详情按钮状态

export const GETCLASSIFYGOODSLIST = 'GETCLASSIFYGOODSLIST' // 获取分类商品列表

export const UPDATECHOOSEDSKUINFO = 'UPDATECHOOSEDSKUINFO' // 选择SKU