
export const GETHOMEPAGEDATA = 'GETHOMEPAGEDATA' // 获取首页信息

export const SETPREVPATHNAME = 'SETPREVPATHNAME' // 如果上一页是地址页面就保存

export const SETINDEXSCROLLPOSITION = 'SETINDEXSCROLLPOSITION' // 设置首页的滚动条位置
